/**
 * Smoke test: visit every top-level Odoo app and verify it loads.
 *
 * This test dynamically reads the menu registry (generated by kctl-odoo e2e discover)
 * or falls back to a static list of common Odoo apps.
 */

import { test, expect } from "../../fixtures/odoo-test";
import * as fs from "fs";
import * as path from "path";

// ---------------------------------------------------------------------------
// Load menu registry or use static fallback
// ---------------------------------------------------------------------------

interface MenuItem {
  id: number;
  name: string;
  path: string;
  action: string;
}

interface MenuRegistry {
  topLevelApps: Array<{ id: number; name: string; webIcon: string }>;
  menuItems: MenuItem[];
}

function loadMenuRegistry(): MenuRegistry | null {
  const registryPath = path.resolve(__dirname, "../../odoo-menu-registry.json");
  if (fs.existsSync(registryPath)) {
    return JSON.parse(fs.readFileSync(registryPath, "utf-8"));
  }
  return null;
}

// Static fallback: common Odoo 18 apps and their URL paths
const STATIC_APPS = [
  { name: "Discuss", path: "/odoo/discuss" },
  { name: "Sales", path: "/odoo/sales" },
  { name: "Invoicing", path: "/odoo/accounting" },
  { name: "Inventory", path: "/odoo/inventory" },
  { name: "Purchase", path: "/odoo/purchase" },
  { name: "CRM", path: "/odoo/crm" },
  { name: "Contacts", path: "/odoo/contacts" },
  { name: "Project", path: "/odoo/project" },
  { name: "Employees", path: "/odoo/employees" },
  { name: "Settings", path: "/odoo/settings" },
];

// ---------------------------------------------------------------------------
// Filter by module if ODOO_E2E_MODULE is set
// ---------------------------------------------------------------------------

function filterByModule(apps: typeof STATIC_APPS): typeof STATIC_APPS {
  const moduleFilter = process.env.ODOO_E2E_MODULE;
  if (!moduleFilter) return apps;

  const moduleLower = moduleFilter.toLowerCase();
  return apps.filter(
    (a) =>
      a.name.toLowerCase().includes(moduleLower) ||
      a.path.toLowerCase().includes(moduleLower),
  );
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

test.describe("Smoke Test: All Menus", () => {
  const registry = loadMenuRegistry();

  if (registry) {
    // Dynamic: test each top-level app from the registry
    const apps = registry.topLevelApps;

    for (const app of apps) {
      test(`load app: ${app.name}`, async ({ page, odoo }) => {
        // Navigate to the home menu and click the app
        await page.goto("/odoo", { waitUntil: "networkidle" });

        // Click the app in the home menu or navbar
        const homeMenu = page.locator(".o_home_menu");
        if (await homeMenu.isVisible({ timeout: 3000 }).catch(() => false)) {
          const appLink = homeMenu
            .locator(".o_app")
            .filter({ hasText: app.name })
            .first();
          if (await appLink.isVisible({ timeout: 2000 }).catch(() => false)) {
            await appLink.click();
          } else {
            test.skip();
            return;
          }
        } else {
          test.skip();
          return;
        }

        await odoo.waitForOdooReady(page);

        // Take screenshot if configured
        if (process.env.ODOO_E2E_SCREENSHOTS === "on") {
          await odoo.takeScreenshot(
            page,
            `app-${app.name.toLowerCase().replace(/\s+/g, "-")}`,
          );
        }

        // Verify no error notification
        const notifications = await odoo.getNotifications(page);
        const errors = notifications.filter(
          (n) =>
            n.toLowerCase().includes("error") ||
            n.toLowerCase().includes("traceback"),
        );
        expect(errors).toHaveLength(0);
      });
    }
  } else {
    // Static fallback: test common apps
    const apps = filterByModule(STATIC_APPS);

    for (const app of apps) {
      test(`load app: ${app.name}`, async ({ page, odoo }) => {
        await page.goto(app.path, { waitUntil: "domcontentloaded" });

        // Should either load successfully or redirect to home
        // (if module not installed, Odoo redirects to /odoo)
        const url = page.url();
        const loaded = url.includes(app.path) || url.includes("/odoo");
        expect(loaded).toBeTruthy();

        // If we landed on the actual page, verify it loaded
        if (url.includes(app.path)) {
          await odoo.waitForOdooReady(page);

          if (process.env.ODOO_E2E_SCREENSHOTS === "on") {
            await odoo.takeScreenshot(
              page,
              `app-${app.name.toLowerCase().replace(/\s+/g, "-")}`,
            );
          }
        }
      });
    }
  }
});
