name: IT Administrator
description: Full IT admin access to all kodemeio services
groups:
  - ak-admin-super
  - ak-admin-app
  - ak-admin-ldap
  - ak-role-admin
  - ak-app-mattermost-all
  - ak-app-mattermost-admin
  - ak-app-odoo-all
  - ak-app-odoo-admin
  - ak-app-grafana-all
  - ak-app-grafana-admin
  - ak-app-n8n-all
  - ak-app-uptime-kuma-all
