name: DevOps Engineer
description: DevOps tools access (Grafana admin, N8N, monitoring)
groups:
  - ak-role-devops
  - ak-role-basic
  - ak-app-mattermost-all
  - ak-app-grafana-all
  - ak-app-grafana-admin
  - ak-app-n8n-all
  - ak-app-uptime-kuma-all
