"""Odoo HRMS webhook setup: create base.automation records via kctl-odoo."""

from __future__ import annotations

import json
import subprocess
from typing import Any

AUTOMATION_NAME = "AK Sync: Employee Provisioning"

_WEBHOOK_CODE_TEMPLATE = """\
# AK Sync: Employee Provisioning Webhook
# Auto-generated by kctl-ak provision setup-webhook
import json
import hashlib
import hmac
import urllib.request

WEBHOOK_URL = "{webhook_url}"
WEBHOOK_SECRET = "{webhook_secret}"
HMAC_KEY = "{hmac_key}"
COMPANY = "{company_code}"

for rec in records:
    email = rec.work_email or ""
    if not email:
        continue

    if not rec.active:
        event = "employee.archive"
    elif rec.create_date == rec.write_date:
        event = "employee.create"
    else:
        event = "employee.unarchive" if rec.active else "employee.archive"

    payload = json.dumps(dict(
        event=event,
        company=COMPANY,
        employee=dict(
            name=rec.name or "",
            email=email,
            department=rec.department_id.name if rec.department_id else "",
            job_title=rec.job_title or "",
            active=rec.active,
        ),
        timestamp=str(fields.Datetime.now()) + "Z",
        source="{hrms_domain}",
    )).encode("utf-8")

    signature = hmac.new(HMAC_KEY.encode(), payload, hashlib.sha256).hexdigest()

    req = urllib.request.Request(
        WEBHOOK_URL,
        data=payload,
        headers=dict(
            **{{"Content-Type": "application/json"}},
            **{{"Authorization": "Bearer " + WEBHOOK_SECRET}},
            **{{"X-Odoo-Signature": signature}},
        ),
    )

    try:
        urllib.request.urlopen(req, timeout=10)
    except Exception as e:
        log("AK Sync webhook failed for %s: %s" % (email, e), level="warning")
"""


def generate_webhook_code(
    webhook_url: str,
    webhook_secret: str,
    hmac_key: str,
    company_code: str,
    hrms_domain: str,
) -> str:
    """Generate Python code for the Odoo automated action."""
    return _WEBHOOK_CODE_TEMPLATE.format(
        webhook_url=webhook_url,
        webhook_secret=webhook_secret,
        hmac_key=hmac_key,
        company_code=company_code,
        hrms_domain=hrms_domain,
    )


def build_automation_vals(
    model_id: int,
    active_field_id: int,
    code: str,
) -> dict[str, Any]:
    """Build the vals dict for base.automation create/write."""
    return {
        "name": AUTOMATION_NAME,
        "model_id": model_id,
        "trigger": "on_create_or_write",
        "trigger_field_ids": [[6, 0, [active_field_id]]],
        "state": "code",
        "active": True,
        "code": code,
    }


def run_kctl_odoo(profile: str, args: list[str]) -> Any:
    """Run kctl-odoo with a profile and return parsed JSON output."""
    cmd = ["kctl-odoo", "--json", "-p", profile] + args
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
    if result.returncode != 0:
        raise RuntimeError(f"kctl-odoo failed: {result.stderr.strip()}")
    return json.loads(result.stdout) if result.stdout.strip() else None


def resolve_model_id(profile: str, model_name: str) -> int:
    """Get ir.model ID for a model name."""
    data = run_kctl_odoo(
        profile,
        [
            "shell",
            "call",
            "ir.model",
            "search_read",
            json.dumps([[["model", "=", model_name]]]),
            "-k",
            json.dumps({"fields": ["id"], "limit": 1}),
        ],
    )
    if not data:
        raise RuntimeError(f"Model not found: {model_name}")
    return data[0]["id"]


def resolve_field_id(profile: str, model_name: str, field_name: str) -> int:
    """Get ir.model.fields ID for a field on a model."""
    data = run_kctl_odoo(
        profile,
        [
            "shell",
            "call",
            "ir.model.fields",
            "search_read",
            json.dumps([[["model", "=", model_name], ["name", "=", field_name]]]),
            "-k",
            json.dumps({"fields": ["id"], "limit": 1}),
        ],
    )
    if not data:
        raise RuntimeError(f"Field not found: {model_name}.{field_name}")
    return data[0]["id"]


def find_existing_automation(profile: str) -> dict[str, Any] | None:
    """Find existing AK Sync automation record, or None."""
    data = run_kctl_odoo(
        profile,
        [
            "shell",
            "call",
            "base.automation",
            "search_read",
            json.dumps([[["name", "=", AUTOMATION_NAME]]]),
            "-k",
            json.dumps({"fields": ["id", "name", "active", "code"], "limit": 1}),
        ],
    )
    if data:
        return data[0]
    return None


def create_automation(profile: str, vals: dict[str, Any]) -> int:
    """Create a base.automation record. Returns record ID."""
    data = run_kctl_odoo(
        profile,
        [
            "shell",
            "call",
            "base.automation",
            "create",
            json.dumps([vals]),
        ],
    )
    return data


def update_automation(profile: str, record_id: int, vals: dict[str, Any]) -> None:
    """Update an existing base.automation record."""
    run_kctl_odoo(
        profile,
        [
            "shell",
            "call",
            "base.automation",
            "write",
            json.dumps([[record_id], vals]),
        ],
    )


def delete_automation(profile: str, record_id: int) -> None:
    """Delete a base.automation record."""
    run_kctl_odoo(
        profile,
        [
            "shell",
            "call",
            "base.automation",
            "unlink",
            json.dumps([[record_id]]),
        ],
    )
